(() => {
  const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
  const W = canvas.width, H = canvas.height;
  const ui = { health: document.querySelector('#healthBar'), kills:document.querySelector('#kills'), timer:document.querySelector('#timer'), score:document.querySelector('#score'), start:document.querySelector('#startScreen'), over:document.querySelector('#gameOver'), result:document.querySelector('#resultLine'), name:document.querySelector('#playerName'), board:document.querySelector('#leaderboard'), note:document.querySelector('#boardNote') };
  const keys = new Set(); let game, last = 0;
  const demoScores = [{name:'BEEPBOOP',score:12750,kills:23,survival_seconds:1250},{name:'SUGAR RUSH',score:9020,kills:16,survival_seconds:1020},{name:'MOP DOG',score:6440,kills:9,survival_seconds:1940},{name:'TOAST',score:4180,kills:7,survival_seconds:680}];
  addEventListener('keydown', e => { keys.add(e.key.toLowerCase()); if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase())) e.preventDefault(); });
  addEventListener('keyup', e => keys.delete(e.key.toLowerCase()));
  function reset(){ game={alive:true,t:0,kills:0,health:100,player:{x:W/2,y:H/2,a:0,bonk:0,vehicle:null},goons:[],cars:[],particles:[],spawn:1.7}; for(let i=0;i<5;i++) spawnGoon(); [['Bubble Bug','#ff6d93'],['Citrus Cab','#ffbd3d'],['Meat Wagon','#cb7bf3']].forEach((v,i)=>game.cars.push({x:170+i*290,y:110+(i%2)*350,name:v[0],color:v[1],a:i*.8,occupied:false,life:100})); updateHud(); }
  function spawnGoon(){ const edge=Math.floor(Math.random()*4), p={x:Math.random()*W,y:Math.random()*H}; if(edge===0)p.y=-30;if(edge===1)p.x=W+30;if(edge===2)p.y=H+30;if(edge===3)p.x=-30; game.goons.push({...p,hp:1,stun:0,hit:0,ram:0,color:['#ff8a64','#c57dff','#f0e45d'][Math.floor(Math.random()*3)]}); }
  function start(){ reset(); ui.start.classList.add('hidden');ui.over.classList.add('hidden'); last=performance.now(); requestAnimationFrame(loop); }
  function loop(now){ if(!game?.alive)return; const dt=Math.min(.033,(now-last)/1000); last=now; update(dt); draw(); requestAnimationFrame(loop); }
  function update(dt){ const p=game.player; game.t+=dt; game.spawn-=dt; if(game.spawn<0){spawnGoon();game.spawn=Math.max(.65,2.1-game.t/240);}
    let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0), dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0); if(dx||dy){let l=Math.hypot(dx,dy);dx/=l;dy/=l;p.a=Math.atan2(dy,dx);}
    const speed=p.vehicle?280:145; p.x=Math.max(16,Math.min(W-16,p.x+dx*speed*dt));p.y=Math.max(16,Math.min(H-16,p.y+dy*speed*dt));
    if((keys.has('e'))&&!p.eLatch){p.eLatch=true; if(p.vehicle){p.vehicle.occupied=false;p.vehicle=null;}else{const c=game.cars.find(c=>!c.occupied&&Math.hypot(c.x-p.x,c.y-p.y)<38);if(c){p.vehicle=c;c.occupied=true;}}} if(!keys.has('e'))p.eLatch=false;
    if(p.vehicle){p.vehicle.x=p.x;p.vehicle.y=p.y;p.vehicle.a=p.a;p.vehicle.life-=dt*1.8;if(p.vehicle.life<=0){p.vehicle.occupied=false;p.vehicle=null;}}
    if(keys.has(' ')&&!p.bonk){p.bonk=.25; bonk();}p.bonk=Math.max(0,p.bonk-dt);
    game.goons.forEach(g=>{const vx=p.x-g.x,vy=p.y-g.y,d=Math.hypot(vx,vy)||1;g.ram-=dt;if(p.vehicle&&d<30&&g.ram<=0){g.hp=0;g.ram=.4;burst(g.x,g.y,g.color);game.kills++;p.vehicle.life-=3;return;}if(g.stun>0){g.stun-=dt;g.x-=vx/d*80*dt;g.y-=vy/d*80*dt;}else{g.x+=vx/d*(30+game.t/65)*dt;if(d<24)game.health-=dt*(p.vehicle?.life?.4:1.8);}}); game.goons=game.goons.filter(g=>g.hp>0); game.particles=game.particles.filter(q=>(q.life-=dt)>0); if(game.health<=0)end(); updateHud(); }
  function bonk(){ const p=game.player, range=p.vehicle?67:42; game.goons.forEach(g=>{const d=Math.hypot(g.x-p.x,g.y-p.y);if(d<range){g.hp--;g.stun=.35;g.hit=.12;burst(g.x,g.y,g.color);if(g.hp<=0)game.kills++;}}); }
  function burst(x,y,c){for(let i=0;i<8;i++)game.particles.push({x,y,vx:(Math.random()-.5)*160,vy:(Math.random()-.5)*160,life:.35,c});}
  function end(){game.alive=false; const s=score();ui.result.textContent=`${Math.floor(game.t)} seconds alive · ${game.kills} knockouts · ${s.toLocaleString()} points`;ui.over.classList.remove('hidden');}
  function score(){return Math.floor(game.t*10)+game.kills*500;}
  function updateHud(){if(!game)return;ui.health.style.width=Math.max(0,game.health)+'%';ui.kills.textContent=String(game.kills).padStart(2,'0');ui.timer.textContent=`${String(Math.floor(game.t/60)).padStart(2,'0')}:${String(Math.floor(game.t%60)).padStart(2,'0')}`;ui.score.textContent=String(score()).padStart(5,'0');}
  function draw(){ctx.fillStyle='#57bcb0';ctx.fillRect(0,0,W,H); ctx.fillStyle='#d5d0b7'; for(let x=0;x<W;x+=190)ctx.fillRect(x,0,52,H); for(let y=35;y<H;y+=165)ctx.fillRect(0,y,W,43); ctx.strokeStyle='#f2e97e';ctx.lineWidth=3;ctx.setLineDash([16,16]);for(let x=26;x<W;x+=190){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}ctx.setLineDash([]);
    for(let x=95;x<W;x+=190)for(let y=92;y<H;y+=165){ctx.fillStyle='#ff7792';ctx.fillRect(x,y,22,10);ctx.fillStyle='#244153';ctx.fillRect(x+4,y+13,14,17);}
    game.cars.forEach(c=>car(c)); game.goons.forEach(g=>{ctx.fillStyle=g.color;ctx.beginPath();ctx.arc(g.x,g.y,11,0,7);ctx.fill();ctx.fillStyle='#173543';ctx.fillRect(g.x-5,g.y-2,3,3);ctx.fillRect(g.x+3,g.y-2,3,3);}); const p=game.player;if(p.bonk){ctx.strokeStyle='#d9ff5c';ctx.lineWidth=5;ctx.beginPath();ctx.arc(p.x,p.y,p.vehicle?55:34,p.a-.7,p.a+.7);ctx.stroke();}if(!p.vehicle){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.a);ctx.fillStyle='#173543';ctx.fillRect(-10,-9,20,18);ctx.fillStyle='#d9ff5c';ctx.fillRect(2,-5,11,10);ctx.restore();} game.particles.forEach(q=>{ctx.fillStyle=q.c;ctx.fillRect(q.x+=q.vx*.016,q.y+=q.vy*.016,4,4);}); }
  function car(c){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.a);ctx.fillStyle='#173543';ctx.fillRect(-22,-13,44,26);ctx.fillStyle=c.color;ctx.fillRect(-19,-10,38,20);ctx.fillStyle='#b5f7f4';ctx.fillRect(-5,-8,13,16);ctx.fillStyle='#173543';ctx.fillRect(-15,-15,8,4);ctx.fillRect(8,-15,8,4);ctx.restore();}
  function renderBoard(rows, remote=false){ui.board.innerHTML=rows.slice(0,5).map((s,i)=>`<li><span class="rank">${String(i+1).padStart(2,'0')}</span><b>${safe(s.name||'RASCAL')}</b><em>${Number(s.score).toLocaleString()}</em></li>`).join('');ui.note.textContent=remote?'Global scores · point total blends time alive and knockouts.':'Local demo scores are shown until Supabase is connected.';}
  function safe(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  async function leaderboard(){const c=window.NEON_MUTT_SUPABASE||{};if(!c.url||!c.anonKey){renderBoard(demoScores);return;}try{const r=await fetch(`${c.url}/rest/v1/scores?select=name,score,kills,survival_seconds&order=score.desc&limit=5`,{headers:{apikey:c.anonKey,Authorization:`Bearer ${c.anonKey}`}});if(!r.ok)throw Error();renderBoard(await r.json(),true);}catch{renderBoard(demoScores);ui.note.textContent='Could not reach the live board. Showing demo scores.';}}
  async function submit(){if(!game)return;const name=(ui.name.value.trim()||'RASCAL').toUpperCase();const entry={name,score:score(),kills:game.kills,survival_seconds:Math.floor(game.t)};const c=window.NEON_MUTT_SUPABASE||{};if(c.url&&c.anonKey){try{await fetch(`${c.url}/rest/v1/scores`,{method:'POST',headers:{apikey:c.anonKey,Authorization:`Bearer ${c.anonKey}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(entry)});}catch{}}else{demoScores.push(entry);}await leaderboard();document.querySelector('#submitScore').textContent='POSTED!';}
  document.querySelector('#startButton').onclick=start;document.querySelector('#againButton').onclick=start;document.querySelector('#submitScore').onclick=submit;document.querySelector('#refreshBoard').onclick=leaderboard;document.querySelector('#helpButton').onclick=()=>document.querySelector('#helpDialog').showModal();document.querySelector('#closeHelp').onclick=()=>document.querySelector('#helpDialog').close();document.querySelectorAll('[data-key]').forEach(button=>{const key=button.dataset.key;const down=e=>{e.preventDefault();keys.add(key);};const up=e=>{e.preventDefault();keys.delete(key);};button.addEventListener('pointerdown',down);button.addEventListener('pointerup',up);button.addEventListener('pointerleave',up);button.addEventListener('pointercancel',up);});renderBoard(demoScores); reset();draw();
})();
